name: Deploy FastAPI Application

on:
  push:
    branches:
      - main  # 或你用于部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    # 连接到远程服务器
    - name: Connetct to Server
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.TOKEN }}
    # 将代码推送到远程服务器
    - name: Push code to server
      run: |
        rsync -avz --delete --exclude '.git' --exclude '.github' . root@${{ secrets.REMOTEHOST }}:/fastapi/tzb/
    # 在远程服务器上安装依赖
    - name: Install dependencies on server
      run: |
        ssh -o StrictHostKeyChecking=no -A root@${{ secrets.REMOTEHOST }} "cd /fastapi/tzb/ && pip install -r requirements.txt"