name: Deploy FastAPI Application

on:
  push:
    branches:
      - main  # 或你用于部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    # 连接到远程服务器
    - name: Connetct to Server
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.TOKEN }}
    - name: Add SSH key to known_hosts
      run: |
        ssh-keyscan ${{ secrets.REMOTEHOST }} >> ~/.ssh/known_hosts
    # 将代码推送到远程服务器
    - name: Create directory structure on server
      run: ssh root@${{ secrets.REMOTEHOST }} "mkdir -p /fastapi/tzb"
    - name: Push code to server
      run: |
        rsync -avz --delete --exclude '.git' --exclude '.github' . root@${{ secrets.REMOTEHOST }}:/fastapi/tzb/
    # 结束远程服务器上的 FastAPI 服务
    - name: Stop FastAPI server
      run: |
        ssh -o StrictHostKeyChecking=no -A root@${{ secrets.REMOTEHOST }} "pkill -f 'gunicorn main:app'"
    # 在远程服务器上安装依赖
    - name: Install dependencies on server
      run: |
        ssh -o StrictHostKeyChecking=no -A root@${{ secrets.REMOTEHOST }} "cd /fastapi/tzb/ &&conda activate tzbpy311 && pip install -r requirements.txt"
    # 启动 FastAPI 服务
    - name: Start FastAPI server
      run: |
        ssh -o StrictHostKeyChecking=no -A root@${{ secrets.REMOTEHOST }} "cd /fastapi/tzb/ && conda activate tzbpy311 && nohup gunicorn main:app --workers 5 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080"
